version: 2.0.{build}.0

install:
  - choco install -y wget
  - wget -q https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe
  - DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

environment:
  NuGetApiKey:
    secure: uNF4gY8KN67ODxKkGPBIz+5MDdf3MRtz4Vi+9McPhWYi4Z6YMQvOcTQRWZYd/N9b

assembly_info:
  patch: true
  file: Shared\SharedAssemblyInfo.cs
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - cmd: cd SharpAdbClient
  - cmd: dotnet restore
  - cmd: dotnet build -c Release --version-suffix beta%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack -c Release --version-suffix beta%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppveyorArtifact "bin\Release\SharpAdbClient.2.1.0-beta$($env:APPVEYOR_BUILD_NUMBER).nupkg"
  - ps: Push-AppveyorArtifact "bin\Release\SharpAdbClient.2.1.0-beta$($env:APPVEYOR_BUILD_NUMBER).symbols.nupkg"

nuget:
  project_feed: true
  account_feed: true

